export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/trail/memories/index',
    'pages/journey/certificate/index',
    'pages/certificate-public/index',
    'pages/mine/orders/index',
    'pages/mine/registrations/index',
    'pages/mine/invoices/index',
    'pages/mine/certificates/index',
    'pages/mine/index',
    'pages/staff/index',
    'pages/staff/checkin/index',
    'pages/auth/login/index',
    'pages/activity/detail/index',
    'pages/activity/series/index',
    'pages/activity/series/detail/index',
    'pages/activity/registration-info/index',
    'pages/activity/qr/index',
    'pages/activity/list/index',
    'pages/trail/index',
    'pages/web-view/index',
  ],
  tabBar: {
    color: '#8A9288',
    selectedColor: '#2E7D5A',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      {
        pagePath: 'pages/index/index',
        text: '首页',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/activity/list/index',
        text: '活动',
        iconPath: 'assets/tabbar/route.png',
        selectedIconPath: 'assets/tabbar/route-active.png',
      },
      {
        pagePath: 'pages/mine/index',
        text: '我的',
        iconPath: 'assets/tabbar/user.png',
        selectedIconPath: 'assets/tabbar/user-active.png',
      },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#F7F8F5',
    navigationBarTitleText: '行者学社',
    navigationBarTextStyle: 'black',
  },
})
