export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/trail/index',
    'pages/trail/memories/index',
    'pages/journey/certificate/index',
    'pages/mine/orders/index',
    'pages/mine/registrations/index',
    'pages/mine/invoices/index',
    'pages/mine/certificates/index',
    'pages/mine/index',
    'pages/staff/index',
    'pages/staff/checkin/index',
    'pages/auth/login/index',
    'pages/activity/detail/index',
    'pages/activity/registration-info/index',
    'pages/activity/qr/index',
    'pages/activity/list/index',
  ],
  tabBar: {
    color: '#8A9288',
    selectedColor: '#2E7D5A',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      { pagePath: 'pages/index/index', text: '首页' },
      { pagePath: 'pages/trail/index', text: '行者之路' },
      { pagePath: 'pages/mine/index', text: '我的' },
    ],
  },
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#F7F6F2',
    navigationBarTitleText: '行者学社',
    navigationBarTextStyle: 'black',
  },
})
